
###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services?page=0&size=10

###
http://geobike.xyz/api/services

###
POST http://localhost:3000/api/services
Content-Type: application/json

{
    "s_id":"9",
    "s_name":"Llantas"
}

###
GET http://localhost:3000/api/services/7

###
DELETE  http://localhost:3000/api/services/8

###
PUT http://localhost:3000/api/services/7
Content-Type: application/json

{
    "s_name":"Venta de Bicicletas de Carreras"
}


###
POST http://localhost:3000/api/workshops
Content-Type: application/json

{    
    "name":"Taller Calle 50",
    "address":"Calle 61 # 9",
    "latitude":"4.6468638928244120",
    "longitude":"-74.06257584239731",
    "type":"5",
    "votes": 5,
    "services":["Taller bicicletas gamma baja","Repuestos","Mantenimiento","Accesorios"]
}

###
GET http://localhost:3000/api/workshops

###
POST http://localhost:3000/api/uservotes
Content-Type: application/json

{
    "workshopId": 1,
    "userId": 1,
    "vote":  1,
    "typeVote":  1
}

###
PUT http://localhost:3000/api/workshopvote/1
Content-Type: application/json

{
    "votes": null
}

###
DELETE http://localhost:3000/api/workshops/5


###
GET http://localhost:3000/Developer
