
###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services?page=0&size=10

###
http://geobike.xyz/api/services

###
POST http://localhost:3000/api/services
Content-Type: application/json

{
    "s_id":"8",
    "s_name":"Acompañamiento"
}

###
GET http://localhost:3000/api/services/7

###
DELETE  http://localhost:3000/api/services/8

###
PUT http://localhost:3000/api/services/7
Content-Type: application/json

{
    "s_name":"Venta de Bicicletas de Carreras"
}

###
GET http://localhost:3000/api/workshops
